// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $(window).ready(function() {
    var fontAPIURL, fontFamilies, fontFamilySorting, fontsNotYetLoaded, initializeFontLoading, loadFont, yourAPIkey;

    yourAPIkey = 'InsertYourAPIkey';
    fontFamilySorting = 'popularity';
    fontAPIURL = 'https://www.googleapis.com/webfonts/v1/webfonts';
    fontFamilies = [];
    fontsNotYetLoaded = [];
    $.getJSON("" + fontAPIURL + "?sort=" + fontFamilySorting + "&key=" + yourAPIkey, function(data) {
      var i, output;

      output = "<ul>";
      for (i in data.items) {
        if (__indexOf.call(data.items[i].subsets, "latin") >= 0 && __indexOf.call(data.items[i].variants, "regular") >= 0) {
          output += "<li style='font-family:\"" + data.items[i].family + "\", Helvetica'><input type='radio' name='fontselection' value='" + data.items[i].family + "' id='" + data.items[i].family + "' /><label for='" + data.items[i].family + "'>" + data.items[i].family + "</label></li>";
          fontFamilies.push(data.items[i].family);
        }
      }
      output += "</ul>";
      document.getElementById("wrapper").innerHTML = output;
      return initializeFontLoading(fontFamilies);
    });
    initializeFontLoading = function(fontList) {
      var font, fontsToAdd, fontsToAddString, fontsToAddText, i, s, _i, _ref;

      fontsToAdd = [];
      for (i = _i = 0, _ref = fontList.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (!(i < 20)) {
          continue;
        }
        font = fontList.shift();
        fontsToAdd.push(font);
      }
      fontsToAddString = fontsToAdd.join('|');
      fontsToAddText = fontsToAddString.replace("|", "");
      window.WebFontConfig = {
        google: {
          families: [fontsToAddString],
          text: [fontsToAddText]
        },
        active: function() {
          if (fontList.length > 0) {
            return loadFont(fontList);
          }
        },
        inactive: function() {
          fontsNotYetLoaded.push(font);
          if (fontList.length > 0) {
            return loadFont(fontList);
          }
        },
        timeout: 500
      };
      s = document.createElement('script');
      s.src = "" + (document.location.protocol === 'https:' ? 'https' : 'http') + "://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";
      s.type = 'text/javascript';
      s.async = 'true';
      return document.body.appendChild(s);
    };
    return loadFont = function(fontList) {
      var font, fontsToAdd, fontsToAddString, fontsToAddText, i, _i, _ref;

      fontsToAdd = [];
      for (i = _i = 0, _ref = fontList.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (!(i < 20)) {
          continue;
        }
        font = fontList.shift();
        fontsToAdd.push(font);
      }
      fontsToAddString = fontsToAdd.join('|');
      fontsToAddText = fontsToAddString.replace("|", "");
      console.log(fontsToAddText);
      return WebFont.load({
        google: {
          families: [fontsToAddString],
          text: [fontsToAddText]
        },
        active: function() {
          if (fontList.length > 0) {
            return loadFont(fontList);
          }
        },
        inactive: function() {
          fontsNotYetLoaded.push(font);
          if (fontList.length > 0) {
            return loadFont(fontList);
          }
        },
        timeout: 500
      });
    };
  });

}).call(this);
